fix errcheck linting
Some of these were a slightly false positive, because flagSet.parseLongArg
uses a named output var which was already assigned to `err`, and `flagSet.fail()`
returns the error-as is; https://github.com/spf13/pflag/blob/10438578954bba2527fe5cae3684d4532b064bbe/flag.go#L935-L942

    flag.go:1033:9: Error return value of `f.fail` is not checked (errcheck)
            f.fail(err)
                  ^
    flag.go:1109:9: Error return value of `f.fail` is not checked (errcheck)
            f.fail(err)
                  ^

This patch just re-assigns it to `err` to keep the linters happy.

Many other unhandled errors were either "neglectable" (e.g. errors from
`fmt.Printf`), and some unhandled errors would likely cause tests to fail
later on, but it doesn't hurt to be explicit and to explicitly mark unhandled
errors.

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>